/**
 * Copy the third-party CSS, JS, and font files the templates need out of
 * node_modules and into app/static/vendor/.
 *
 * The app is documented as a trusted-LAN tool that should sit behind a
 * firewall, but base.html used to pull Bootstrap, Bootstrap Icons, and Inter
 * from jsdelivr and Google Fonts -- so an isolated network lost the
 * stylesheet, the icons, and the typeface, and every page load told two third
 * parties who was using the app. Serving them from /static removes both
 * problems and drops the interactive dependency on a CDN staying up.
 *
 * Everything here is copied byte for byte from the pinned packages. Nothing is
 * hand-edited, so upgrading is `npm install` plus a rebuild, and CI's
 * `git diff --exit-code` proves the checked-in copies still match the
 * packages named in package-lock.json.
 */

import { mkdir, copyFile, readFile, writeFile, rm } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const vendor = path.join(root, 'app', 'static', 'vendor');
const modules = path.join(root, 'node_modules');

/** Inter weights the design system actually uses: body 400, headings/labels 600. */
const INTER_FACES = [
  'latin-400',
  'latin-600',
  'latin-ext-400',
  'latin-ext-600',
];

async function copyInto(from, to) {
  await mkdir(path.dirname(to), { recursive: true });
  await copyFile(from, to);
  return path.relative(root, to).split(path.sep).join('/');
}

async function main() {
  // Rebuild from scratch so a removed upstream file cannot linger in git.
  await rm(vendor, { recursive: true, force: true });

  const written = [];

  written.push(await copyInto(
    path.join(modules, 'bootstrap', 'dist', 'css', 'bootstrap.min.css'),
    path.join(vendor, 'bootstrap', 'bootstrap.min.css'),
  ));
  written.push(await copyInto(
    path.join(modules, 'bootstrap', 'dist', 'js', 'bootstrap.bundle.min.js'),
    path.join(vendor, 'bootstrap', 'bootstrap.bundle.min.js'),
  ));

  // bootstrap-icons.css asks for ./fonts/*, so the directory shape has to
  // survive the copy. Both formats ship: the CSS is unmodified, and leaving a
  // dangling woff reference in it would be a worse trade than the extra file.
  written.push(await copyInto(
    path.join(modules, 'bootstrap-icons', 'font', 'bootstrap-icons.css'),
    path.join(vendor, 'bootstrap-icons', 'bootstrap-icons.css'),
  ));
  for (const file of ['bootstrap-icons.woff2', 'bootstrap-icons.woff']) {
    written.push(await copyInto(
      path.join(modules, 'bootstrap-icons', 'font', 'fonts', file),
      path.join(vendor, 'bootstrap-icons', 'fonts', file),
    ));
  }

  // Fontsource ships one stylesheet per subset/weight. Concatenating them
  // keeps base.html to a single <link> without editing any of the @font-face
  // rules; their url()s stay relative to ./files/, which is preserved below.
  const interCss = [];
  for (const face of INTER_FACES) {
    const source = path.join(modules, '@fontsource', 'inter', `${face}.css`);
    interCss.push((await readFile(source, 'utf8')).trim());
    for (const ext of ['woff2', 'woff']) {
      written.push(await copyInto(
        path.join(modules, '@fontsource', 'inter', 'files', `inter-${face}-normal.${ext}`),
        path.join(vendor, 'inter', 'files', `inter-${face}-normal.${ext}`),
      ));
    }
  }
  const interTarget = path.join(vendor, 'inter', 'inter.css');
  await mkdir(path.dirname(interTarget), { recursive: true });
  await writeFile(
    interTarget,
    `/* Generated by scripts/vendor-assets.mjs from @fontsource/inter. Do not edit. */\n`
      + `${interCss.join('\n\n')}\n`,
    'utf8',
  );
  written.push('app/static/vendor/inter/inter.css');

  written.sort();
  console.log(`vendored ${written.length} files into app/static/vendor/`);
  for (const file of written) console.log(`  ${file}`);
}

await main();
